create database summer_intern;

\c summer_intern 

CREATE TABLE COLLEGE
(	Name VARCHAR(25)  NOT NULL,
	Address VARCHAR(30), 
	Email_Id VARCHAR(30),
	Principal VARCHAR(20) NOT NULL,
	Contact_Number VARCHAR(10) NOT NULL,
	PRIMARY KEY (Name));
	
CREATE TABLE DEPARTMENT
(	Dname VARCHAR(30)  NOT NULL,
	DId INT NOT NULL, 
	HOD VARCHAR(20) NOT NULL,
	No_of_students INT NOT NULL,
	Cname VARCHAR(25) NOT NULL,
	Mgr_id INT NOT NULL,
	PRIMARY KEY (DId),
	UNIQUE (Dname), 
	FOREIGN KEY (Cname) REFERENCES COLLEGE(Name)) ;
	
CREATE TABLE DEPT_LOCATIONS
(	DId INT NOT NULL, 
	Dlocation VARCHAR(25) NOT NULL,
	PRIMARY KEY (DId, Dlocation),
	FOREIGN KEY (DId) REFERENCES DEPARTMENT(DId));

CREATE TABLE FACULTY
(	
	Fid INT NOT NULL,
	Fname VARCHAR(25) NOT NULL ,
	Domain1 VARCHAR(20) NOT NULL,
	Contact VARCHAR(10),
	Email_Id VARCHAR(20),
	Dnum INT NOT NULL,
	PRIMARY KEY (Fid),
	FOREIGN KEY (Dnum) REFERENCES DEPARTMENT(DId));
	
CREATE TABLE DOMAIN1
(	Code VARCHAR(15)  NOT NULL,
	Name VARCHAR(40) NOT NULL,
	No_of_credits INT NOT NULL, 
	Faculty VARCHAR(25) NOT NULL,
	D_num INT NOT NULL,
	PRIMARY KEY (Code),
	UNIQUE(Name),
	FOREIGN KEY (D_num) REFERENCES DEPARTMENT(DId));
	
CREATE TABLE PROJECT
(	Pname VARCHAR(25)  NOT NULL,
	Domain1 VARCHAR(20) NOT NULL,
	Duration INT,
	Status VARCHAR(10) NOT NULL,
	Domain_code VARCHAR(15) NOT NULL,
	F_id INT NOT NULL,
	PRIMARY KEY (Pname),
	FOREIGN KEY (Domain_code) REFERENCES DOMAIN1(Code),
	FOREIGN KEY (F_id) REFERENCES FACULTY(Fid));
	
CREATE TABLE STUDENT
(	Fname VARCHAR(15) NOT NULL,
	Lname VARCHAR(15),
	SRN VARCHAR(15) NOT NULL,
	Birth_date DATE,
	Sem_sec VARCHAR(10) NOT NULL,
	Cgpa NUMERIC(2,1) NOT NULL,
	Contact VARCHAR(10) NOT NULL,
	Year_of_grad INT NOT NULL,
	Email_id VARCHAR(25),
	Dno INT NOT NULL,
	Proj_name VARCHAR,
	PRIMARY KEY (SRN),
	FOREIGN KEY (Dno) REFERENCES DEPARTMENT(DId),
	FOREIGN KEY (Proj_name) REFERENCES PROJECT(Pname));	
	
CREATE TABLE INTERNSHIP
(	Iname VARCHAR(25) NOT NULL,
	Contact VARCHAR(10) NOT NULL, 
	Email_id VARCHAR(25),
	Address VARCHAR(25),
	Domain1 VARCHAR(15) NOT NULL,
	S_srn VARCHAR(15) NOT NULL,
	PRIMARY KEY (Iname),
	FOREIGN KEY (S_srn) REFERENCES STUDENT(SRN));
	
	
CREATE TABLE WORKS_ON
(	Ssrn VARCHAR(15) NOT NULL,
	P_name VARCHAR NOT NULL, 
	Start_date DATE,
	PRIMARY KEY (Ssrn, P_name),
	FOREIGN KEY (Ssrn) REFERENCES STUDENT(SRN),
	FOREIGN KEY(P_name) REFERENCES PROJECT(Pname));
